### ISSUE TITLE
Short IV infusion

### ISSUE THREAD

**Issue by cohanlon2** [andrewhooker/PopED#41] opened 2019-10-24 22:52 UTC
Hi Andrew,

I am having trouble implementing a short IV infusion. The rationale for wanting to do this being that an IV ‘bolus’ is actually given over a period of time e.g. 3 minutes. 
Using the code you posted on 11 Jul 2017, with low values of TINF = 0.5, the model prediction graph seems to miss some of the subsequent doses. 
If TINF = 1, there doesn’t seem to be this problem. 
The issue seems to depend on the DOSE/TINF value (and therefore the amount “In”).

Do you have any suggestions getting this short IV infusion to work?

Best,
Conor

_Originally posted by @cohanlon2 in https://github.com/andrewhooker/PopED/issues/11#issuecomment-546133755_

**Comment by andrewhooker** [comment] 2019-10-29 10:23
Duplicate of #11 (comment)

**Closed by andrewhooker** 2019-10-29 10:23 UTC
